invpend:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controller for slider2cart joint-----------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: slider_to_cart
    pid: {p: 5.0, i: 0.0, d: 20.0}
    publish_rate: 50
  # Position Controller for cart2pole joint-----------------------------------
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: cart_to_pole
    pid: {p: 150.0, i: 0.0, d: 80.0}
    publish_rate: 50
